### ISSUE TITLE
502 bad gateway when calling Context::storage()

### ISSUE THREAD

**Issue by kiper0808** [opentelemetry-php/contrib-auto-yii#2]
Hello guys, the application freezes when I click on the Google Auth button (yii\authclient\clients\GoogleOAuth) and displays 502 bad gateway if I have auto-instrumentation enabled.  In the logs: Maximum execution time of 30+2 seconds exceeded (terminated) in /app/vendor/yiisoft/yii2/base/BaseObject.php on line 106

In nginx logs:
[error] 20#20: *22 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.10.4.1, server: localhost, request: "GET ..../auth?authclient=google

This happens when calling **Context::storage()**
https://github.com/opentelemetry-php/contrib-auto-yii/blob/main/src/YiiInstrumentation.php#L123

PHP 8.0
Nginx 1.18
Yii2 2.0.37
open-telemetry/sdk 1.0.7
opentelemetry-auto-yii 0.0.2

**Comment by brettmc** [comment]
Hello.
I've got an idea of might be going on here. If a pre or post hook throws an exception or error (which can be language-level errors, such as a type not matching a type-hint), then PHP can hang.
We've just released 1.0.1beta1 of the opentelemetry extension, which handles most of those cases (and it looks like a PR has just been raised to improve it more).
So, firstly can you re-rest with 1.0.1beta1 of the extension - it might still fail, but (hopefully) not hang, and you might be able to find a message logged to PHP's error log with some details of the error and where it came from. With that info we can dig further into what's going on and where the bug is.

**Comment by kiper0808** [comment]
Updated version to 1.0.1beta1, but the logs did not appear, I’m temporarily ignoring this file. If the problem is resolved in the future, I will be grateful, but now it’s not critical

**Comment by brettmc** [comment]
Can you provide a reproduction case, or at least instructions on how to reproduce the error?

**Comment by kiper0808** [comment]
1. You need to select Google in the Authentication collection in Yii2:
```php
        'authClientCollection' => [
            'class' => 'yii\authclient\Collection',
            'clients' => [
                'google' => [
                    'class' => 'yii\authclient\clients\Google',
                ],
            ],
        ],
``` 
2.  Set button:
```php
                '<li>'
                . yii\authclient\widgets\AuthChoice::widget([
                    'popupMode' => true,
                ])
                . '</li>'
``` 
3. Click the button
Then you will get Yii2 application hang.

**Comment by brettmc** [comment]
@kiper0808 I just noticed that this issue has been logged against our read-only mirror. Nobody is going to see it here (and I forgot to disable issues when I created the repo). Can you please raise this over in https://github.com/open-telemetry/opentelemetry-php/issues if it is still a problem for you? You'll need to provide a self-contained reproduction, I don't know what to do with the code you supplied before.
